# Mandatory
server:
  port: 6002

# Mandatory.
cache:
  host: "localhost"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 0

# Optional.
responseCache:
  mongoURL: "mongodb://tvast:password@localhost:27017/protocol_server-v2?authSource=admin"
  ttl: "PT10S"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
#  synchronous:
#    mongoURL: "mongodb://tvast:password@localhost:27017/protocol_server-v2?authSource=admin"

  webhook:
    url: "http://localhost:80/search"

  #messageQueue:
  #  amqpURL: "amqp://guest:guest@localhost:5672"
  #  incomingQueue: "protocol-server-incoming"
  #  outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bpp

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "inbox-bpp"
    outboxQueue: "outbox-bpp"
    amqpURL: "amqp://tvast:password@127.0.0.1:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl : "PT10S"
      init:
        ttl : "PT10S"
      select:
        ttl : "PT10S"
      confirm:
        ttl : "PT10S"
      status:
        ttl : "PT10S"
      track:
        ttl : "PT10S"
      cancel:
        ttl : "PT10S"
      update:
        ttl : "PT10S"
      rating:
        ttl : "PT10S"
      support:
        ttl : "PT10S"
      get_cancellation_reasons:
        ttl: "PT10S"
      get_rating_categories:
        ttl: "PT10S"

    responses:
      on_search:
        ttl: "PT15S"
      on_init:
        ttl: "PT10S"
      on_select:
        ttl: "PT10S"
      on_confirm:
        ttl: "PT10S"
      on_status:
        ttl: "PT10S"
      on_track:
        ttl: "PT10S"
      on_cancel:
        ttl: "PT10S"
      on_update:
        ttl: "PT10S"
      on_rating:
        ttl: "PT10S"
      on_support:
        ttl: "PT10S"
      cancellation_reasons:
        ttl: "PT10S"
      rating_categories:
        ttl: "PT10S"

  # Mandatory.
  privateKey: "kSFdrsFeppO1H2jMLkObdaGANzP3/rkimhEfhMMkR84ctc+n0/nJ9CeOev6L1xcsYHv62POBFun6L3LyBYiCsg=="
  publicKey: "HLXPp9P5yfQnjnr+i9cXLGB7+tjzgRbp+i9y8gWIgrI="

  # Mandatory.
  subscriberId: "chargepe-bpp"
  subscriberUri: "http://demand.uei.chargepe.io"

  # Mandatory.
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "chargepe-bpp-key"

  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2
  telemetry:
    enabled: false
    url: ""
    batchSize: 100
    # In minutes
    syncInterval: 30
    redis_db: 3
